// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type HealthStateGetter struct {
	HealthStateStringStub        func(ip string) string
	healthStateStringMutex       sync.RWMutex
	healthStateStringArgsForCall []struct {
		ip string
	}
	healthStateStringReturns struct {
		result1 string
	}
	healthStateStringReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HealthStateGetter) HealthStateString(ip string) string {
	fake.healthStateStringMutex.Lock()
	ret, specificReturn := fake.healthStateStringReturnsOnCall[len(fake.healthStateStringArgsForCall)]
	fake.healthStateStringArgsForCall = append(fake.healthStateStringArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("HealthStateString", []interface{}{ip})
	fake.healthStateStringMutex.Unlock()
	if fake.HealthStateStringStub != nil {
		return fake.HealthStateStringStub(ip)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.healthStateStringReturns.result1
}

func (fake *HealthStateGetter) HealthStateStringCallCount() int {
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	return len(fake.healthStateStringArgsForCall)
}

func (fake *HealthStateGetter) HealthStateStringArgsForCall(i int) string {
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	return fake.healthStateStringArgsForCall[i].ip
}

func (fake *HealthStateGetter) HealthStateStringReturns(result1 string) {
	fake.HealthStateStringStub = nil
	fake.healthStateStringReturns = struct {
		result1 string
	}{result1}
}

func (fake *HealthStateGetter) HealthStateStringReturnsOnCall(i int, result1 string) {
	fake.HealthStateStringStub = nil
	if fake.healthStateStringReturnsOnCall == nil {
		fake.healthStateStringReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.healthStateStringReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *HealthStateGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	return fake.invocations
}

func (fake *HealthStateGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
